### PR TITLE
add Spik3r and Dinor3x EV3Dev2 programs

### PR DESCRIPTION
**Pull request by AntoniLuongPham**
Dear repo owners,

I would like to contribute my SPIK3R EV3Dev2 program for your consideration. Please let me have your feedback.

Thank you very much!

Antoni

### CODE REVIEW

**Comment by WasabiFan** [comment]
Hi! Just wanted to mention I haven't taken the time to look over the two PRs yet but they aren't forgotten. Looks good at a glance, I just need to set aside some time to confirm :smile:

**Comment by AntoniLuongPham** [comment]
@WasabiFan thank you very much, please let me know if there're things I need to do better. There is no hurry, as you are very busy.

**Comment by AntoniLuongPham** [comment]
Dear @WasabiFan,

Please also find my new Dinor3x program submitted for your review.

I have enjoyed building and programming this robot very much. I like its walking by legs without wheels.

Thank you very much! :)

Antoni

**Comment by WasabiFan** [comment]
These seem pretty well-done! I appreciate you taking the time to get them together and open PRs. I don't have these robots built to test them out, but it sounds like you have them working on your end

**Comment by TheVinhLuong102** [comment]
@WasabiFan thank you so much for the merges!

@AntoniLuongPham is my son and has been building and programming the Home Edition robots from the start of summer. We've tried various Python APIs (ev3dev/ev3dev2, pybricks) and thought we would contribute our programs to you as we go along. It's also a great exercise for @AntoniLuongPham in terms of doing quality work that meets some high standards. :)

I've been helping and guiding @AntoniLuongPham quite a bit in this process (he's 6 :) ), especially in organizing files/folders, using GitHub and submitting PRs. But @AntoniLuongPham did the coding himself, and went through lots of revisions with my review before submitting.

We are working on the Home Edition Fan Robots and usually finish building and programming another robot every 2-3 weeks. We will submit our new programs for your review.

Thank you again @WasabiFan!

Vinh

**Pull request merged**
