### PR TITLE
Moves the console_menu.py demo from ev3dev/ev3dev-lang-python/utils to here

### PR DESCRIPTION
**Pull request by gideongrinberg**
Moves the console menu demo from python-lang/utils to the demos. This demonstrates LEDs, console and buttons.

### CODE REVIEW

**Comment by WasabiFan** [comment]
Thanks! Did you test it to make sure it works?

**Comment by gideongrinberg** [comment]
Yes I did. I am still trying to add a feature that allows multiple choices.

**Comment by gideongrinberg** [comment]
I left it the same as the file from utils in the python bindings repo.

**Comment by WasabiFan** [comment]
Thanks!

**Pull request merged**
