### PR TITLE
Add link to video from original implementation (MindCub3r README)

### PR DESCRIPTION
**Pull request by bittner**
I found an alternative implementation that might be worth documenting. It also sports a demo video to show off the ev3dev-powered robot.

Would be cool if you integrated that into your README.

### CODE REVIEW

**Comment by dwalton76** [comment]
Long story short, the MINDCUBER implementation here is somewhat based on the cavenel MINDCUBER implementation.  When I wanted to do MINDCUBER in ev3dev I found the cavenel code but it was way out of date and did not work. I did a bunch of work on it and got it working...I forget when but at some point I forked it and started working on that fork in ev3dev-lang-python.  The code was eventually moved to this repo when we decided to separate the demo code.

**Comment by bittner** [comment]
Okay, that's fine. But how about including a reference to the YouTube video?

Not that I want to help YouTube make advertising money, but videos in general increase motivation to start working on that specific robot, don't they?
  
**EDIT:**  The video link could mention your historical review from above in a very short sentence, in brackets.

**Comment by dwalton76** [comment]
@bittner I think linking to the video would be fine

**Comment by bittner** [comment]
Fine like this?

**Comment by bittner** [comment]
Any objections? Should I still change something?

A side-note
-------------
My son just noticed that the brick is mounted in an unhandy direction. When mounted on the flip side the SD card would be directly accessible (which would be advantageous when you work with ev3dev as a temporary replacement for the LEGO firmware). The video shows the same flaw, because it follows the original building instructions. It might be a good idea to change this in both the building instructions and the ev3dev program (switch ports if you keep the same cables). Then a new video may come handy to avoid confusion.

**Comment by dwalton76** [comment]
Sorry for being slow to respond...looks good to me.

Regarding flipping the EV3 brick around in the build instructions, it is probably more trouble than it is worth.  David Gilday designed MINDCUB3R and hosts the build instructions so you would need to reach out to him to get them changed.

**Pull request merged**
